/* Generate the store-fold format-pair verdict table from the
   exhaustive proof RESULT files.
   Copyright (C) 2026 Tenstorrent Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 3, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

/* Generator for the format-pair verdict ladders of
   gimple-rvtt-store-fold.cc (the S2 sink admission and the licensed
   stochrnd fold's matching-precision pair_ok) used to be if-else
   chains transcribing tt/proofs verdicts by hand.  This tool
   regenerates tt/rvtt-storefold-verdicts.def from the ladders'
   SOURCES OF TRUTH:

     argv[1]  tt/proofs/store-sink-roundtrip/RESULT.txt
     argv[2]  tt/proofs/stochrnd-store-round/RESULT.txt
     argv[3]  output .def path

   The build (tt/t-riscv-tt rvtt-storefold-verdicts.chk) re-runs this
   tool and byte-compares its output with the checked-in .def: a
   RESULT file that changes without regeneration+review, or a hand
   edit of the .def, FAILS THE BUILD.  "Retire the rule if the RESULT
   stops being EQUAL" (tt/proofs/README.md) is thereby a build fact --
   the tool derives each pair's fire class from the RESULT verdict and
   divergence census, so a changed verdict changes the generated bytes.

   Policy encoded here (the reviewed pass policy, now in one place):
     - verdict EQUAL (no mismatch over the full input space)
	 -> FIRE: the value-preserving sink is licensed by the proof
	    alone.
     - verdict NOT-EQUAL with every mismatch in the denormal-flush
       class
	 -> LICENSED: fires only under -mtt-tensix-optimize-store-sink
	    (owner ratification 2026-08-26, scoped to exactly this
	    divergence class).
     - verdict NOT-EQUAL with any mismatch outside that class
	 -> REFUSE: outside the ratified scope (the WH INT32_SM pair's
	    negative-zero divergence), refuses with or without the
	    license token.
     - the SRCB store format resolves at RUNTIME to one of the swept
       float paths (the row's ALU config owns the
       resolution), so the emitted SRCB row carries the
       MOST REFUSING class of the swept float pairs (FP16/BF16/FP32).
     - each stochrnd proof row pairs one SFPSTOCHRND float conversion
       with its matching-precision store Mod0 (that pairing IS the
       sweep's definition); an SRCB pair is emitted per conversion
       under the same runtime-resolution policy.

   Mod0/Mod1 numeric encodings are transcribed to the symbolic
   capability constants (BlackholeA0 SFPSTORE.md/SFPLOAD.md and
   SFPSTOCHRND.md supporting definitions; the same values
   gimple-rvtt-store-fold.cc / rvtt-protos.h define):
     store/load Mod0: 0 SRCB, 1 FP16, 2 BF16, 3 FP32, 4 INT32,
		      12 INT32_SM
     stochrnd Mod1 conversion: fp16a 0, fp16b 1.
   An unknown encoding in a RESULT file is a hard error: the table or
   the transcription would be wrong, and this tool refuses to guess.  */

#include "bconfig.h"
#include "system.h"

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace {

/* ---------------- SHA256 (FIPS 180-4), for the RESULT file
   commitment recorded in the generated header.  */

struct sha256 {
  uint32_t h[8] = { 0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
		    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19 };
  unsigned char buf[64];
  size_t buflen = 0;
  uint64_t total = 0;

  static uint32_t rotr (uint32_t x, unsigned n)
  { return (x >> n) | (x << (32 - n)); }

  void block (const unsigned char *p)
  {
    static const uint32_t k[64] = {
      0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b,
      0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01,
      0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7,
      0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
      0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152,
      0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
      0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
      0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
      0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819,
      0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08,
      0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f,
      0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
      0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2 };
    uint32_t w[64];
    for (unsigned i = 0; i != 16; i++)
      w[i] = (uint32_t (p[4 * i]) << 24) | (uint32_t (p[4 * i + 1]) << 16)
	| (uint32_t (p[4 * i + 2]) << 8) | uint32_t (p[4 * i + 3]);
    for (unsigned i = 16; i != 64; i++)
      {
	uint32_t s0 = rotr (w[i - 15], 7) ^ rotr (w[i - 15], 18)
	  ^ (w[i - 15] >> 3);
	uint32_t s1 = rotr (w[i - 2], 17) ^ rotr (w[i - 2], 19)
	  ^ (w[i - 2] >> 10);
	w[i] = w[i - 16] + s0 + w[i - 7] + s1;
      }
    uint32_t a = h[0], b = h[1], c = h[2], d = h[3];
    uint32_t e = h[4], f = h[5], g = h[6], hh = h[7];
    for (unsigned i = 0; i != 64; i++)
      {
	uint32_t s1 = rotr (e, 6) ^ rotr (e, 11) ^ rotr (e, 25);
	uint32_t ch = (e & f) ^ (~e & g);
	uint32_t t1 = hh + s1 + ch + k[i] + w[i];
	uint32_t s0 = rotr (a, 2) ^ rotr (a, 13) ^ rotr (a, 22);
	uint32_t maj = (a & b) ^ (a & c) ^ (b & c);
	uint32_t t2 = s0 + maj;
	hh = g; g = f; f = e; e = d + t1;
	d = c; c = b; b = a; a = t1 + t2;
      }
    h[0] += a; h[1] += b; h[2] += c; h[3] += d;
    h[4] += e; h[5] += f; h[6] += g; h[7] += hh;
  }

  void update (const void *data, size_t len)
  {
    const unsigned char *p = (const unsigned char *) data;
    total += len;
    while (len)
      {
	size_t take = 64 - buflen;
	if (take > len)
	  take = len;
	memcpy (buf + buflen, p, take);
	buflen += take;
	p += take;
	len -= take;
	if (buflen == 64)
	  {
	    block (buf);
	    buflen = 0;
	  }
      }
  }

  std::string final ()
  {
    uint64_t bits = total * 8;
    unsigned char pad = 0x80;
    update (&pad, 1);
    unsigned char zero = 0;
    while (buflen != 56)
      update (&zero, 1);
    unsigned char len8[8];
    for (unsigned i = 0; i != 8; i++)
      len8[i] = (unsigned char) (bits >> (56 - 8 * i));
    /* Bypass 'total' accounting for the length words.  */
    memcpy (buf + 56, len8, 8);
    block (buf);
    char out[65];
    for (unsigned i = 0; i != 8; i++)
      snprintf (out + 8 * i, 9, "%08x", h[i]);
    return std::string (out, 64);
  }
};

/* ---------------- input handling.  */

struct input {
  std::string path;		/* as given */
  std::string cite;		/* tail path for citation comments */
  std::vector<std::string> lines;
  std::string filehash;
};

static bool
read_input (const char *path, input *in)
{
  FILE *fd = fopen (path, "rb");
  if (!fd)
    {
      fprintf (stderr, "genrvtt-storefold: cannot read %s\n", path);
      return false;
    }
  std::string all;
  char chunk[4096];
  size_t got;
  while ((got = fread (chunk, 1, sizeof chunk, fd)) != 0)
    all.append (chunk, got);
  fclose (fd);

  sha256 sh;
  sh.update (all.data (), all.size ());
  in->filehash = sh.final ();
  in->path = path;

  /* Citation path: the trailing <dir>/<file> under tt/proofs/.  */
  in->cite = path;
  size_t at = in->cite.rfind ("proofs/");
  if (at != std::string::npos)
    in->cite = in->cite.substr (at + 7);

  size_t start = 0;
  while (start < all.size ())
    {
      size_t eol = all.find ('\n', start);
      if (eol == std::string::npos)
	eol = all.size ();
      in->lines.push_back (all.substr (start, eol - start));
      start = eol + 1;
    }
  return true;
}

/* Numeric field after TAG on LINE, or -1.  */

static long
field_after (const std::string &line, const char *tag)
{
  size_t at = line.find (tag);
  if (at == std::string::npos)
    return -1;
  return strtol (line.c_str () + at + strlen (tag), nullptr, 10);
}

/* The hex commitment after "sha256 =" / "sha256  =", or "".  */

static std::string
sha_field (const std::string &line)
{
  size_t at = line.find ("sha256");
  if (at == std::string::npos)
    return "";
  at = line.find ('=', at);
  if (at == std::string::npos)
    return "";
  ++at;
  while (at < line.size () && line[at] == ' ')
    ++at;
  size_t end = at;
  while (end < line.size () && ISXDIGIT (line[end]))
    ++end;
  return line.substr (at, end - at);
}

/* ---------------- the store-sink round-trip pairs.  */

/* Divergence census of one swept pair.  */
struct census {
  long swept = -1;
  long total = -1;
  long denormal = 0;
  long negzero = 0;
  long nan = 0;
  long other = 0;
};

struct sink_pair {
  long lmod = -1, smod = -1;
  std::string desc;
  census c;
  std::string verdict;		/* EQUAL / NOT-EQUAL */
  std::string roundtrip_sha, identity_sha;
};

static const char *
mod0_name (long mod0)
{
  switch (mod0)
    {
    case 0: return "SFPMEM_MOD0_FMT_SRCB";
    case 1: return "SFPMEM_MOD0_FMT_FP16";
    case 2: return "SFPMEM_MOD0_FMT_BF16";
    case 3: return "SFPMEM_MOD0_FMT_FP32";
    case 4: return "SFPMEM_MOD0_FMT_INT32";
    case 12: return "SFPMEM_MOD0_FMT_INT32_SM";
    default: return nullptr;
    }
}

/* The divergence class of a census: the single mismatch class every
   mismatch falls in, NONE for a clean sweep, MIXED otherwise.  */

static const char *
divergence_class (const census &c)
{
  if (c.total == 0)
    return "NONE";
  if (c.total == c.denormal && !c.negzero && !c.nan && !c.other)
    return "DENORMAL_FLUSH";
  if (c.total == c.negzero && !c.denormal && !c.nan && !c.other)
    return "NEGATIVE_ZERO";
  return "MIXED";
}

/* The fire class the pass policy gives a (verdict, divergence) pair --
   see the file comment.  */

static const char *
license_class (const std::string &verdict, const char *divergence)
{
  if (verdict == "EQUAL")
    return "FIRE";
  if (strcmp (divergence, "DENORMAL_FLUSH") == 0)
    return "LICENSED";
  return "REFUSE";
}

static bool
parse_sink_pairs (const input &in, std::vector<sink_pair> *out)
{
  sink_pair cur;
  bool open = false;
  auto flush = [&] () -> bool
  {
    if (!open)
      return true;
    if (cur.lmod < 0 || cur.smod < 0 || cur.c.total < 0
	|| cur.verdict.empty () || cur.roundtrip_sha.empty ()
	|| cur.identity_sha.empty ())
      {
	fprintf (stderr, "genrvtt-storefold: %s: incomplete pair block"
		 " (load mod0=%ld, store mod0=%ld)\n",
		 in.path.c_str (), cur.lmod, cur.smod);
	return false;
      }
    out->push_back (cur);
    cur = sink_pair ();
    return true;
  };

  for (const std::string &line : in.lines)
    {
      if (line.compare (0, 6, "pair (") == 0)
	{
	  if (!flush ())
	    return false;
	  open = true;
	  cur.lmod = field_after (line, "load mod0=");
	  cur.smod = field_after (line, "store mod0=");
	  size_t at = line.find (')');
	  if (at != std::string::npos)
	    {
	      at++;
	      while (at < line.size () && line[at] == ' ')
		at++;
	      cur.desc = line.substr (at);
	    }
	}
      else if (!open)
	continue;
      else if (line.find ("inputs swept") != std::string::npos)
	cur.c.swept = field_after (line, ":");
      else if (line.find ("total mismatches") != std::string::npos)
	cur.c.total = field_after (line, ":");
      else if (line.find ("denormal") != std::string::npos)
	cur.c.denormal = field_after (line, ":");
      else if (line.find ("negative zero") != std::string::npos)
	cur.c.negzero = field_after (line, ":");
      else if (line.find ("NaN") != std::string::npos)
	cur.c.nan = field_after (line, ":");
      else if (line.find ("other") != std::string::npos)
	cur.c.other = field_after (line, ":");
      else if (line.find ("verdict") != std::string::npos)
	{
	  size_t at = line.find (':');
	  if (at != std::string::npos)
	    {
	      at++;
	      while (at < line.size () && line[at] == ' ')
		at++;
	      size_t end = line.find_last_not_of (" \t");
	      cur.verdict = line.substr (at, end + 1 - at);
	    }
	}
      else if (line.find ("roundtrip-stream") != std::string::npos)
	cur.roundtrip_sha = sha_field (line);
      else if (line.find ("identity-stream") != std::string::npos)
	cur.identity_sha = sha_field (line);
    }
  return flush ();
}

/* ---------------- the stochrnd store rows.  */

struct stochrnd_row {
  char tag = 0;			/* 'A', 'B', ... */
  std::string conv;		/* fp16a / fp16b */
  long smod = -1;
  std::string verdict;
  std::string fused_sha, direct_sha;
};

static const char *
conv_name (const std::string &conv)
{
  if (conv == "fp16a")
    return "SFPSTOCHRND_MOD1_FP32_TO_FP16A";
  if (conv == "fp16b")
    return "SFPSTOCHRND_MOD1_FP32_TO_FP16B";
  return nullptr;
}

static bool
parse_stochrnd_rows (const input &in, std::vector<stochrnd_row> *out)
{
  for (const std::string &line : in.lines)
    {
      if (line.compare (0, 4, "row ") == 0
	  && line.find ("STOCHRND") != std::string::npos)
	{
	  stochrnd_row r;
	  r.tag = line[4];
	  size_t at = line.find ("fp32->");
	  if (at != std::string::npos)
	    {
	      at += 6;
	      size_t end = at;
	      while (end < line.size () && ISALNUM (line[end]))
		end++;
	      r.conv = line.substr (at, end - at);
	    }
	  r.smod = field_after (line, "STORE mod0=");
	  out->push_back (r);
	}
      else if (line.find ("verdict") != std::string::npos && !out->empty ()
	       && out->back ().verdict.empty ())
	{
	  size_t at = line.find (':');
	  if (at != std::string::npos)
	    {
	      at++;
	      while (at < line.size () && line[at] == ' ')
		at++;
	      size_t end = line.find_last_not_of (" \t");
	      out->back ().verdict = line.substr (at, end + 1 - at);
	    }
	}
      else if (line.compare (0, 3, "row") == 0
	       && line.find ("stream sha256") != std::string::npos)
	for (stochrnd_row &r : *out)
	  if (line.compare (0, 4, std::string ("row") + r.tag) == 0)
	    {
	      if (line.find ("fused-stream") != std::string::npos)
		r.fused_sha = sha_field (line);
	      else if (line.find ("direct-stream") != std::string::npos)
		r.direct_sha = sha_field (line);
	    }
    }
  for (const stochrnd_row &r : *out)
    if (r.conv.empty () || r.smod < 0 || r.verdict.empty ()
	|| r.fused_sha.empty () || r.direct_sha.empty ())
      {
	fprintf (stderr, "genrvtt-storefold: %s: incomplete row %c\n",
		 in.path.c_str (), r.tag ? r.tag : '?');
	return false;
      }
  return true;
}

}

int
main (int argc, const char **argv)
{
  if (argc != 4)
    {
      fprintf (stderr, "usage: genrvtt-storefold"
	       " store-sink-RESULT stochrnd-RESULT output.def\n");
      return 1;
    }

  input sink_in, rnd_in;
  if (!read_input (argv[1], &sink_in) || !read_input (argv[2], &rnd_in))
    return 1;

  std::vector<sink_pair> pairs;
  if (!parse_sink_pairs (sink_in, &pairs) || pairs.empty ())
    {
      fprintf (stderr, "genrvtt-storefold: no pair blocks in %s\n", argv[1]);
      return 1;
    }
  std::vector<stochrnd_row> rows;
  if (!parse_stochrnd_rows (rnd_in, &rows) || rows.empty ())
    {
      fprintf (stderr, "genrvtt-storefold: no rows in %s\n", argv[2]);
      return 1;
    }

  /* Validate encodings up front: refuse to guess.  */
  for (const sink_pair &p : pairs)
    {
      if (p.lmod != p.smod)
	{
	  fprintf (stderr, "genrvtt-storefold: %s: pair (%ld,%ld) is not a"
		   " same-format round trip; the S2 ladder has no mixed-pair"
		   " row (mixed pairs are format-unproven by absence)\n",
		   argv[1], p.lmod, p.smod);
	  return 1;
	}
      if (!mod0_name (p.lmod))
	{
	  fprintf (stderr, "genrvtt-storefold: %s: unknown Mod0 %ld\n",
		   argv[1], p.lmod);
	  return 1;
	}
      if (p.verdict != "EQUAL" && p.verdict != "NOT-EQUAL")
	{
	  fprintf (stderr, "genrvtt-storefold: %s: unknown verdict '%s'\n",
		   argv[1], p.verdict.c_str ());
	  return 1;
	}
      if ((p.verdict == "EQUAL") != (p.c.total == 0)
	  || (p.c.total == 0) != (p.roundtrip_sha == p.identity_sha))
	{
	  fprintf (stderr, "genrvtt-storefold: %s: pair (%ld,%ld): verdict,"
		   " mismatch census and stream commitments disagree\n",
		   argv[1], p.lmod, p.smod);
	  return 1;
	}
    }
  for (const stochrnd_row &r : rows)
    {
      if (!conv_name (r.conv) || !mod0_name (r.smod))
	{
	  fprintf (stderr, "genrvtt-storefold: %s: row %c: unknown"
		   " conversion '%s' or Mod0 %ld\n",
		   argv[2], r.tag, r.conv.c_str (), r.smod);
	  return 1;
	}
      if (r.verdict != "NOT-EQUAL" || r.fused_sha == r.direct_sha)
	{
	  fprintf (stderr, "genrvtt-storefold: %s: row %c is not the proven"
		   " divergent class the license quantifies (verdict '%s');"
		   " the licensed pairing policy must be re-reviewed, not"
		   " regenerated\n", argv[2], r.tag, r.verdict.c_str ());
	  return 1;
	}
    }

  /* The SRCB runtime-resolution class: most refusing over the swept
     float pairs (FIRE < LICENSED < REFUSE).  */
  auto rank = [] (const char *lic) -> int
  {
    return strcmp (lic, "FIRE") == 0 ? 0
      : strcmp (lic, "LICENSED") == 0 ? 1 : 2;
  };
  int srcb_rank = -1;
  bool srcb_not_equal = false;
  bool srcb_mixed = false;
  const char *srcb_class = "NONE";
  unsigned floats_seen = 0;
  for (const sink_pair &p : pairs)
    if (p.lmod == 1 || p.lmod == 2 || p.lmod == 3)
      {
	floats_seen++;
	const char *div = divergence_class (p.c);
	const char *lic = license_class (p.verdict, div);
	if (rank (lic) > srcb_rank)
	  srcb_rank = rank (lic);
	if (p.verdict == "NOT-EQUAL")
	  srcb_not_equal = true;
	if (strcmp (srcb_class, "NONE") == 0)
	  srcb_class = div;
	else if (strcmp (srcb_class, div) != 0
		 && strcmp (div, "NONE") != 0)
	  srcb_mixed = true;
      }
  if (floats_seen != 3)
    {
      fprintf (stderr, "genrvtt-storefold: %s: expected the three swept"
	       " float pairs (FP16/BF16/FP32), found %u -- the SRCB"
	       " runtime-resolution row cannot be derived\n",
	       argv[1], floats_seen);
      return 1;
    }
  const char *srcb_lic = srcb_rank == 0 ? "FIRE"
    : srcb_rank == 1 ? "LICENSED" : "REFUSE";
  if (srcb_mixed)
    srcb_class = "MIXED";

  FILE *out = fopen (argv[3], "w");
  if (!out)
    {
      fprintf (stderr, "genrvtt-storefold: cannot write %s\n", argv[3]);
      return 1;
    }

  fprintf (out,
	   "/* Dst store-fold format-pair verdicts -*- mode: c++ -*-\n"
	   "   Generated automatically by genrvtt-storefold from the\n"
	   "   exhaustive proof sweeps -- DO NOT EDIT.\n"
	   "\n"
	   "   Copyright (C) 2026 Tenstorrent Inc.\n"
	   "\n"
	   "   This file is part of GCC.\n"
	   "\n"
	   "   GCC is free software; you can redistribute it and/or modify"
	   " it under\n"
	   "   the terms of the GNU General Public License as published by"
	   " the Free\n"
	   "   Software Foundation; either version 3, or (at your option)"
	   " any later\n"
	   "   version.\n"
	   "\n"
	   "   GCC is distributed in the hope that it will be useful, but"
	   " WITHOUT ANY\n"
	   "   WARRANTY; without even the implied warranty of"
	   " MERCHANTABILITY or\n"
	   "   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public"
	   " License\n"
	   "   for more details.\n"
	   "\n"
	   "   You should have received a copy of the GNU General Public"
	   " License\n"
	   "   along with GCC; see the file COPYING3.  If not see\n"
	   "   <http://www.gnu.org/licenses/>.\n"
	   "\n"
	   "   Sources of truth (SHA256 of the RESULT bytes at generation"
	   " time):\n"
	   "     tt/proofs/%s\n"
	   "       %s\n"
	   "     tt/proofs/%s\n"
	   "       %s\n"
	   "\n"
	   "   Regenerate: `make rvtt-storefold-verdicts-regen` in the gcc\n"
	   "   build directory (writes back into the source tree).  Every\n"
	   "   build regenerates into a scratch file and BYTE-COMPARES it\n"
	   "   against this checked-in table (tt/t-riscv-tt\n"
	   "   rvtt-storefold-verdicts.chk): if a RESULT file changes, or\n"
	   "   this file is edited by hand, the build fails loudly -- the\n"
	   "   tt/proofs/README.md \"retire the rule if the RESULT stops\n"
	   "   being EQUAL\" contract as a build fact, and the transcription\n"
	   "   fidelity of every row below as a machine check.\n"
	   "\n"
	   "   RVTT_STOREFOLD_SINK_PAIR (lfmt, sfmt, verdict, divergence,\n"
	   "				license, roundtrip_sha, identity_sha)\n"
	   "     One S2-sink admission row per proven (load Mod0, store"
	   " Mod0)\n"
	   "     Dst round trip; license = FIRE (EQUAL pair) / LICENSED\n"
	   "     (denormal-flush class, -mtt-tensix-optimize-store-sink"
	   " only) /\n"
	   "     REFUSE (divergence outside the ratified class).  Pairs"
	   " without\n"
	   "     a row refuse store-fold-sink-format-unproven.\n"
	   "   RVTT_STOCHRND_STORE_PAIR (conv_mod1, store_mod0, fused_sha,\n"
	   "			       direct_sha)\n"
	   "     One licensed matching-precision pairing for the stochrnd\n"
	   "     store fold's pair_ok (-mtt-tensix-optimize-stochrnd-store-"
	   "fold).\n"
	   "\n"
	   "   SRCB rows carry no stream commitment of their own: the SRCB\n"
	   "   store resolves at runtime to one of the swept float paths"
	   " (the\n"
	   "   row's ALU config owns the resolution)"
	   " --\n"
	   "   their class is derived as the most refusing of the swept"
	   " float\n"
	   "   pairs.  */\n"
	   "\n",
	   sink_in.cite.c_str (), sink_in.filehash.c_str (),
	   rnd_in.cite.c_str (), rnd_in.filehash.c_str ());

  fprintf (out, "RVTT_STOREFOLD_PROOF (\"%s\", \"%s\")\n",
	   sink_in.cite.c_str (), sink_in.filehash.c_str ());
  fprintf (out, "RVTT_STOREFOLD_PROOF (\"%s\", \"%s\")\n\n",
	   rnd_in.cite.c_str (), rnd_in.filehash.c_str ());

  for (const sink_pair &p : pairs)
    {
      const char *div = divergence_class (p.c);
      const char *lic = license_class (p.verdict, div);
      fprintf (out, "/* %s: %ld mismatch%s / %ld swept.  */\n",
	       p.desc.c_str (), p.c.total, p.c.total == 1 ? "" : "es",
	       p.c.swept);
      fprintf (out, "RVTT_STOREFOLD_SINK_PAIR (%s, %s, %s, %s, %s,\n"
	       "\t\t\t  \"%s\",\n"
	       "\t\t\t  \"%s\")\n",
	       mod0_name (p.lmod), mod0_name (p.smod),
	       p.verdict == "EQUAL" ? "EQUAL" : "NOT_EQUAL",
	       div, lic,
	       p.roundtrip_sha.c_str (), p.identity_sha.c_str ());
    }
  fprintf (out, "/* SRCB, runtime-resolved to a swept float path.  */\n");
  fprintf (out, "RVTT_STOREFOLD_SINK_PAIR (SFPMEM_MOD0_FMT_SRCB,"
	   " SFPMEM_MOD0_FMT_SRCB, %s, %s, %s,\n\t\t\t  \"-\", \"-\")\n\n",
	   srcb_not_equal ? "NOT_EQUAL" : "EQUAL", srcb_class, srcb_lic);

  for (const stochrnd_row &r : rows)
    {
      fprintf (out, "/* row %c: fp32->%s nearest vs the bare mod0=%ld"
	       " store.  */\n", r.tag, r.conv.c_str (), r.smod);
      fprintf (out, "RVTT_STOCHRND_STORE_PAIR (%s, %s,\n"
	       "\t\t\t  \"%s\",\n"
	       "\t\t\t  \"%s\")\n",
	       conv_name (r.conv), mod0_name (r.smod),
	       r.fused_sha.c_str (), r.direct_sha.c_str ());
      fprintf (out, "RVTT_STOCHRND_STORE_PAIR (%s, SFPMEM_MOD0_FMT_SRCB,"
	       " \"-\", \"-\")\n", conv_name (r.conv));
    }

  fclose (out);
  return 0;
}
