// The _lv instructions MUST follow the non-live versions of the same instruction

SFPU_BUILTIN (sfpassign_lv,    RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpassignlr,     RISCV_V64SF_FTYPE_USI,                         sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpload,         RISCV_V64SF_FTYPE_POINTER_USI_USI,             sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpload_lv,      RISCV_V64SF_FTYPE_POINTER_V64SF_USI_USI,       sfpu, 0, 1, 0)
SFPU_BUILTIN (sfploadi,        RISCV_V64SF_FTYPE_POINTER_USI_USI,             sfpu, 0, 0, 0)
SFPU_BUILTIN (sfploadi_lv,     RISCV_V64SF_FTYPE_POINTER_V64SF_USI_USI,       sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpmov,          RISCV_V64SF_FTYPE_V64SF_USI,                   sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpmov_lv,       RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpmul,          RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpmul_lv,       RISCV_V64SF_FTYPE_V64SF_V64SF_V64SF_USI,       sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpadd,          RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpadd_lv,       RISCV_V64SF_FTYPE_V64SF_V64SF_V64SF_USI,       sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpmuli,         RISCV_V64SF_FTYPE_POINTER_V64SF_USI_USI,       sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpaddi,         RISCV_V64SF_FTYPE_POINTER_V64SF_USI_USI,       sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpiadd_v,       RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 1, 0, 1)
SFPU_BUILTIN (sfpiadd_i,       RISCV_V64SF_FTYPE_POINTER_V64SF_USI_USI,       sfpu, 1, 0, 0)
SFPU_BUILTIN (sfpiadd_i_lv,    RISCV_V64SF_FTYPE_POINTER_V64SF_V64SF_USI_USI, sfpu, 1, 1, 0)
SFPU_BUILTIN (sfpshft_v,       RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpshft_i,       RISCV_V64SF_FTYPE_POINTER_V64SF_USI,           sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpabs,          RISCV_V64SF_FTYPE_V64SF_USI,                   sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpabs_lv,       RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpand,          RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpor,           RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpnot,          RISCV_V64SF_FTYPE_V64SF,                       sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpnot_lv,       RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 1, 0)
SFPU_BUILTIN (sfplz,           RISCV_V64SF_FTYPE_V64SF_USI,                   sfpu, 0, 0, 0)
SFPU_BUILTIN (sfplz_lv,        RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 1, 1, 0)
SFPU_BUILTIN (sfpsetexp_v,     RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpsetexp_i,     RISCV_V64SF_FTYPE_POINTER_USI_V64SF,           sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpsetexp_i_lv,  RISCV_V64SF_FTYPE_POINTER_V64SF_USI_V64SF,     sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpsetman_v,     RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpsetman_i,     RISCV_V64SF_FTYPE_POINTER_USI_V64SF,           sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpsetman_i_lv,  RISCV_V64SF_FTYPE_POINTER_V64SF_USI_V64SF,     sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpsetsgn_v,     RISCV_V64SF_FTYPE_V64SF_V64SF,                 sfpu, 0, 0, 1)
SFPU_BUILTIN (sfpsetsgn_i,     RISCV_V64SF_FTYPE_POINTER_USI_V64SF,           sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpsetsgn_i_lv,  RISCV_V64SF_FTYPE_POINTER_V64SF_USI_V64SF,     sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpmad,          RISCV_V64SF_FTYPE_V64SF_V64SF_V64SF_USI,       sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpmad_lv,       RISCV_V64SF_FTYPE_V64SF_V64SF_V64SF_V64SF_USI, sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpdivp2,        RISCV_V64SF_FTYPE_POINTER_USI_V64SF_USI,       sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpdivp2_lv,     RISCV_V64SF_FTYPE_POINTER_V64SF_USI_V64SF_USI, sfpu, 0, 1, 0)
SFPU_BUILTIN (sfpexexp,        RISCV_V64SF_FTYPE_V64SF_UHI,                   sfpu, 1, 0, 0)
SFPU_BUILTIN (sfpexexp_lv,     RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 1, 1, 0)
SFPU_BUILTIN (sfpexman,        RISCV_V64SF_FTYPE_V64SF_UHI,                   sfpu, 0, 0, 0)
SFPU_BUILTIN (sfpexman_lv,     RISCV_V64SF_FTYPE_V64SF_V64SF_USI,             sfpu, 0, 1, 0)
SFPU_BUILTIN (sfplut,          RISCV_V64SF_FTYPE_V64SF_V64SF_V64SF_V64SF_USI, sfpu, 0, 0, 1)

SFPU_NO_TGT_BUILTIN (sfpkeepalive,   RISCV_VOID_FTYPE_V64SF_USI,              sfpu, 0, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpsetcc_i,     RISCV_VOID_FTYPE_USI_USI,                sfpu, 1, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpsetcc_v,     RISCV_VOID_FTYPE_V64SF_USI,              sfpu, 1, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpencc,        RISCV_VOID_FTYPE_USI_USI,                sfpu, 1, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpcompc,       RISCV_VOID_FTYPE,                        sfpu, 1, 0, 0)
SFPU_NO_TGT_BUILTIN (sfppushc,       RISCV_VOID_FTYPE,                        sfpu, 0, 0, 0)
SFPU_NO_TGT_BUILTIN (sfppopc,        RISCV_VOID_FTYPE,                        sfpu, 1, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpstore,       RISCV_VOID_FTYPE_POINTER_V64SF_USI_USI,  sfpu, 0, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpnop,         RISCV_VOID_FTYPE,                        sfpu, 0, 0, 0)
SFPU_NO_TGT_BUILTIN (sfpillegal,     RISCV_VOID_FTYPE,                        sfpu, 0, 0, 0)

#undef SFPU_BUILTIN
#undef SFPU_NO_TGT_BUILTIN
